const Courses = [
    {
        id: "1",
        image: require("../assets/Web-Development.jpg"),
        title: "Web Development",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
        course1: "HTML5",
        course2: "CSS3",
        course3: "JavaScript",
        price: 5000,
    },
    {
        id: "2",
        image: require("../assets/Graphic.png"),
        title: "Graphic Designing",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
        course1: "Adobe Illustrator",
        course2: "Adobe Photoshop",
        course3: "Adobe Xd",
        price: 4000,
    },
    {
        id: "3",
        image: require("../assets/Coding.jpg"),
        title: "Coding Fundamentals",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
        course1: "JavaScript",
        course2: "Algorithm",
        course3: "Data Structure",
        price: 2000,
    },
    {
        id: "4",
        image: require("../assets/Hacking.jpg"),
        title: "Ethical Hacking",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
        course1: "Testing",
        course2: "Linux OS",
        course3: "Exploitation",
        price: 6000,
    },
    {
        id: "5",
        image: require("../assets/Video-editing.jpg"),
        title: "Video Editing",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
        course1: "Adobe Premier Pro",
        course2: "Nero Video",
        course3: "Apple Final Cut Pro",
        price: 3000,
    },
    {
        id: "6",
        image: require("../assets/App-development.jpg"),
        title: "App Development",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
        course1: "React Native",
        course2: "Firebase",
        course3: "Nodejs",
        price: 6000,
    },
];
export default Courses;